#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6444733942                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : it                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Traccia i tuoi abbonamenti

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Andrea Montinovo                                
your_link                                 : https://montinovo.com                    
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Monitoraggio semplice
    description                           : Tieni traccia di tutti i tuoi abbonamenti in un unico posto.
    fontawesome_icon_name                 : list-alt
    
  - title                                 : Promemoria di pagamento
    description                           : Ricevi notifiche prima dei rinnovi, così puoi scegliere se disdire.
    fontawesome_icon_name                 : bell

  - title                                 : Visualizza le tue spese
    description                           : Scopri dove vanno i tuoi soldi con grafici e statistiche dettagliate.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Scopri i costi nascosti
    description                           : Identifica gli abbonamenti dimenticati e risparmia denaro.
    fontawesome_icon_name                 : search

  - title                                 : Configurazione facile
    description                           : Aggiungi gli abbonamenti in un attimo.
    fontawesome_icon_name                 : plus-circle

  - title                                 : Dashboard personalizzata
    description                           : Ottieni una panoramica chiara delle tue spese di abbonamento.
    fontawesome_icon_name                 : tachometer-alt

  - title                                 : Analisi intelligenti
    description                           : Monitora le tendenze di spesa e individua le aree in cui puoi risparmiare.
    fontawesome_icon_name                 : brain

  - title                                 : Avvisi proattivi
    description                           : Ricevi promemoria prima del rinnovo automatico degli abbonamenti.
    fontawesome_icon_name                 : exclamation-triangle

  - title                                 : Monitoraggio illimitato degli abbonamenti
    description                           : Gestisci tutti i tuoi abbonamenti senza limiti.
    fontawesome_icon_name                 : infinity

  - title                                 : Categorie personalizzabili
    description                           : Organizza gli abbonamenti per tipo per un facile budget.
    fontawesome_icon_name                 : tags

  - title                                 : Supporto multivaluta
    description                           : Tieni traccia degli abbonamenti nella tua valuta locale.
    fontawesome_icon_name                 : dollar-sign




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
